# Generated by Django 5.1.7 on 2025-03-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_createdat_conversation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='auto_named',
            field=models.BooleanField(default=False),
        ),
    ]
